# Generated by Django 4.1.6 on 2023-02-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=50)),
                ('pic', models.ImageField(max_length=500, upload_to='')),
                ('date', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cake_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_id', models.IntegerField()),
                ('by_flavour', models.CharField(max_length=100)),
                ('by_type', models.CharField(max_length=100)),
                ('by_ocassion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('cake_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('user_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=40)),
                ('passwd', models.CharField(max_length=40)),
                ('confirmpasswd', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=50)),
                ('cake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.cake_type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.registration')),
            ],
        ),
        migrations.CreateModel(
            name='cake_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.CharField(max_length=50)),
                ('card_no', models.CharField(max_length=50)),
                ('cvv', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('cake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.cake_type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.registration')),
            ],
        ),
        migrations.CreateModel(
            name='cake_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(max_length=50)),
                ('bdt', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.cake_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.registration')),
            ],
        ),
    ]
