# Generated by Django 4.1.2 on 2023-03-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake_order',
            old_name='bdt',
            new_name='abdt',
        ),
        migrations.RenameField(
            model_name='cake_order',
            old_name='cake',
            new_name='cake_id',
        ),
        migrations.RenameField(
            model_name='cake_order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='cake_details',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cake_payment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='amt',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pin',
        ),
        migrations.AlterField(
            model_name='cake_details',
            name='date',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cake_type',
            name='cake_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.cake_details'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
