# Generated by Django 4.1.6 on 2023-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0002_rename_bdt_cake_order_abdt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_details',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
