# Generated by Django 4.1.2 on 2023-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0003_cake_details_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cakeimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
