# Generated by Django 4.1.2 on 2023-03-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0004_cakeimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_details',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
