# Generated by Django 4.1.2 on 2023-03-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0005_alter_cake_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_details',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
