# Generated by Django 4.1.2 on 2023-03-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0006_cake_details_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake_details',
            name='timestamp',
        ),
    ]
