# Generated by Django 4.1.2 on 2023-03-24 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0007_remove_cake_details_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_details',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
