# Generated by Django 4.1.2 on 2023-04-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0008_alter_cake_details_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake_order',
            name='review',
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_decp', models.CharField(max_length=50)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.cake_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.registration')),
            ],
        ),
    ]
