# Generated by Django 4.1.2 on 2023-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0009_remove_cake_order_review_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
