# Generated by Django 4.1.2 on 2023-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0010_delete_rating_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
