# Generated by Django 4.1.2 on 2023-05-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0012_remove_cart_cake_id_remove_cart_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('order processing', 'order processing'), ('order on the way', 'order confirm'), ('order completed', 'order on the way'), ('order recived', 'order recived'), ('order cancelled', 'order\xa0cancelled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(default='ssss', max_length=100)),
                ('mobile', models.CharField(default='45678', max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='cake_order',
        ),
    ]
