# Generated by Django 4.1.6 on 2023-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0013_orders_delete_cake_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake_details',
            name='caption',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
