# Generated by Django 4.1.2 on 2023-05-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0014_cake_details_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='revieww',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_decp', models.CharField(max_length=50)),
                ('rating', models.IntegerField(null=True)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.cake_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devas.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
