# Generated by Django 4.1.6 on 2023-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devas', '0015_revieww_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revieww',
            name='cake',
            field=models.CharField(max_length=50),
        ),
    ]
